language: python
env:
  - TOXENV=py27-unittests
  - TOXENV=py33-unittests
  - TOXENV=py34-unittests
  - TOXENV=lint
install:
  - pip install tox
  - pip install codecov
  - pip install coveralls
  - npm install -g jshint
script:
  - tox
  - jshint .
after_success:
  - coveralls
  - codecov
