site_name: PyMdown Documentation
repo_url: https://github.com/facelessuser/PyMdown
site_description: A Python Markdown Preview and Converter Tool
copyright: Copyright &copy; 2014 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
  - Home: index.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Markdown Syntax: user-guide/markdown-syntax.md
    - General Usage: user-guide/general-usage.md
    - Pygments Customization: user-guide/pygments-customization.md
  - Contributing &amp; Suppport: contributing.md
  - License: license.md
theme: readthedocs
theme_dir: doc_theme
markdown_extensions:
  - markdown.extensions.toc
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.githubemoji
  - pymdownx.tasklist
  - pymdownx.progressbar
  - pymdownx.headeranchor
  - pymdownx.arithmatex
  - pymdownx.mark
  - pymdownx.critic
